### ISSUE TITLE
Unwanted decapitalisation

### ISSUE THREAD

**Issue by florismarel** [DesignBites/oep#13]
Organisation name and purpose should not be decapitalised (happens on page 6)

**Comment by onurmatik** [comment]
Page 6 refers to the sixth page of the flow, i.e. https://designbites.aalto.fi/mapper/6/ right?
Seems to be working for me. 
![Screen Shot 2021-02-04 at 2 48 47 PM](https://user-images.githubusercontent.com/127720/106888930-52ae2880-66f8-11eb-96dc-0f65e28014d5.png)

**Comment by florismarel** [comment]
Yes, it works for me also. I got the feedback from a colleague, but maybe that was an older experience. I'll close the issue.
